import { z } from 'zod';

export const MelissaCensusSchema = z.object({
  ZIP: z.string().max(5).nullable(),
  POPULATION: z.string().max(6).nullable(),
  URBAN: z.string().max(6).nullable(),
  SUBURBAN: z.string().max(6).nullable(),
  FARM: z.string().max(6).nullable(),
  NONFARM: z.string().max(6).nullable(),
  WHITE: z.string().max(6).nullable(),
  BLACK: z.string().max(6).nullable(),
  INDIAN: z.string().max(6).nullable(),
  ASIAN: z.string().max(6).nullable(),
  HAWAIIAN: z.string().max(6).nullable(),
  RACE_OTHER: z.string().max(6).nullable(),
  HISPANIC: z.string().max(6).nullable(),
  AGE_0_4: z.string().max(6).nullable(),
  AGE_5_9: z.string().max(6).nullable(),
  AGE_10_14: z.string().max(6).nullable(),
  AGE_15_17: z.string().max(6).nullable(),
  AGE_18_19: z.string().max(6).nullable(),
  AGE_20: z.string().max(6).nullable(),
  AGE_21: z.string().max(6).nullable(),
  AGE_22_24: z.string().max(6).nullable(),
  AGE_25_29: z.string().max(6).nullable(),
  AGE_30_34: z.string().max(6).nullable(),
  AGE_35_39: z.string().max(6).nullable(),
  AGE_40_44: z.string().max(6).nullable(),
  AGE_45_49: z.string().max(6).nullable(),
  AGE_50_54: z.string().max(6).nullable(),
  AGE_55_59: z.string().max(6).nullable(),
  AGE_60_61: z.string().max(6).nullable(),
  AGE_62_64: z.string().max(6).nullable(),
  AGE_65_66: z.string().max(6).nullable(),
  AGE_67_69: z.string().max(6).nullable(),
  AGE_70_74: z.string().max(6).nullable(),
  AGE_75_79: z.string().max(6).nullable(),
  AGE_80_84: z.string().max(6).nullable(),
  AGE_85_PLS: z.string().max(6).nullable(),
  EDU_LESS9: z.string().max(6).nullable(),
  EDU_9_12: z.string().max(6).nullable(),
  EDU_HIGHSC: z.string().max(6).nullable(),
  EDU_SOMECL: z.string().max(6).nullable(),
  EDU_ASSOC: z.string().max(6).nullable(),
  EDU_BACH: z.string().max(6).nullable(),
  EDU_PROF: z.string().max(6).nullable(),
  HH_INCOME: z.string().max(6).nullable(),
  PC_INCOME: z.string().max(6).nullable(),
  HOUSE_VAL: z.string().max(7).nullable(),
});

export type MelissaCensusInput = z.infer<typeof MelissaCensusSchema>;
