import { z } from 'zod';

export const TellUsMoreSchema = z.object({
  Tell_Us_More_ID: z.number().int(),
  Submitted_Date: z.string().datetime().nullable(),
  Submitted_Time: z.string().nullable(),
  Church_Relationship: z.string().max(2147483647).nullable(),
  Attendance_Frequency: z.string().max(2147483647).nullable(),
  Attendance_Type: z.string().max(2147483647).nullable(),
  Marital_Status: z.string().max(2147483647).nullable(),
  Child_Age_Ranges: z.string().max(2147483647).nullable(),
  Children_Infant: z.boolean(),
  Children_Preschool: z.boolean(),
  Children_Elementary: z.boolean(),
  Children_Middle_School: z.boolean(),
  Children_High_School: z.boolean(),
  Children_19_to_25: z.boolean(),
  Children_Over_25: z.boolean(),
  Children_No: z.boolean(),
  Birth_Year: z.string().max(2147483647).nullable(),
  Postal_Code: z.string().max(2147483647).nullable(),
  Gender: z.string().max(2147483647).nullable(),
  GCC_Source: z.string().max(2147483647).nullable(),
  Friend_Invite_Conditions: z.string().max(2147483647).nullable(),
  Guidance_From_God: z.string().max(2147483647).nullable(),
  Guidance_Work: z.boolean(),
  Guidance_Parenting: z.boolean(),
  Guidance_School: z.boolean(),
  Guidance_Marriage: z.boolean(),
  Guidance_Finances: z.boolean(),
  Guidance_Fun: z.boolean(),
  Guidance_Relationships: z.boolean(),
  Guidance_Boundaries: z.boolean(),
  Guidance_Purpose: z.boolean(),
  Guidance_Other: z.string().max(2147483647).nullable(),
  Generosity: z.string().max(2147483647).nullable(),
  Generosity_Stoppers: z.string().max(2147483647).nullable(),
  Generosity_Stopper_Vision: z.boolean(),
  Generosity_Stopper_Accountability: z.boolean(),
  Generosity_Stopper_Options: z.boolean(),
  Generosity_Stopper_Learn: z.boolean(),
  Generosity_Stopper_Income: z.boolean(),
  Engagement: z.string().max(2147483647).nullable(),
  Engagement_Not_Regular: z.boolean(),
  Engagement_Attends_No_Commitment: z.boolean(),
  Engagement_Committed_Baptized: z.boolean(),
  Engagement_Contributes: z.boolean(),
  Engagement_Makes_Disciples: z.boolean(),
  Engagement_Stoppers: z.string().max(2147483647).nullable(),
  Engagement_Stopper_Family: z.boolean(),
  Engagement_Stopper_Work: z.boolean(),
  Engagement_Stopper_Finances: z.boolean(),
  Engagement_Stopper_Not_Worth_TEAM: z.boolean(),
  Engagement_Stopper_Skeptical: z.boolean(),
  Engagement_Stopper_No_Desire: z.boolean(),
  Engagement_Stoppers_Other: z.string().max(2147483647).nullable(),
  Faith_Growth_Areas: z.string().max(2147483647).nullable(),
  Hope_For_Michiana: z.string().max(2147483647).nullable(),
});

export type TellUsMoreInput = z.infer<typeof TellUsMoreSchema>;
