import { z } from 'zod';

export const WeekendreportdataSchema = z.object({
  "Service Reference Date": z.string().datetime().nullable(),
  Year: z.number().nullable(),
  Attendance: z.number().nullable(),
  "Attendance Kids": z.number().nullable(),
  "Auditorium Only": z.number().nullable(),
  "Total GF": z.number().nullable(),
  "Total Budget": z.number().nullable(),
  "Granger GF": z.number().nullable(),
  "Granger Budget": z.number().nullable(),
  "Elkhart GF": z.number().nullable(),
  "Elkhart Budget": z.number().nullable(),
  "LaPorte GF": z.number().nullable(),
  "LaPorte Budget": z.number().nullable(),
  Building: z.number().nullable(),
  Missions: z.number().nullable(),
  "New Donors Num": z.number().nullable(),
  "New Donor Amt": z.number().nullable(),
  Series: z.string().max(255).nullable(),
  Description: z.string().max(255).nullable(),
  Speaker: z.string().max(255).nullable(),
  "Attendance GRN": z.number().nullable(),
  "GRN Adults TOT": z.number().nullable(),
  "GRN Kids TOT": z.number().nullable(),
  GRN1: z.number().nullable(),
  "GRN1 Kids": z.number().nullable(),
  "GRN1 Auditorium": z.number().nullable(),
  GRN2: z.number().nullable(),
  "GRN2 Kids": z.number().nullable(),
  "GRN2 Auditorium": z.number().nullable(),
  GRN3: z.number().nullable(),
  "GRN3 Kids": z.number().nullable(),
  "GRN3 Auditorium": z.number().nullable(),
  GRN4: z.number().nullable(),
  "GRN4 Kids": z.number().nullable(),
  "GRN4 Auditorium": z.number().nullable(),
  GRN5: z.number().nullable(),
  "GRN5 Kids": z.number().nullable(),
  "GRN5 Auditorium": z.number().nullable(),
  GRN6: z.number().nullable(),
  "GRN6 Kids": z.number().nullable(),
  "GRN6 Auditorium": z.number().nullable(),
  "Attendance ELK": z.number().nullable(),
  "ELK Adults": z.number().nullable(),
  "ELK Kids": z.number().nullable(),
  ELK1: z.number().nullable(),
  "ELK1 Kids": z.number().nullable(),
  "ELK1 Auditorium": z.number().nullable(),
  ELK2: z.number().nullable(),
  "ELK2 Kids": z.number().nullable(),
  "ELK2 Auditorium": z.number().nullable(),
  ELK3: z.number().nullable(),
  "ELK3 Kids": z.number().nullable(),
  "ELK3 Auditorium": z.number().nullable(),
  "Attendance LAP": z.number().nullable(),
  "LAP Adults": z.number().nullable(),
  "LAP Kids": z.number().nullable(),
  LAP1: z.number().nullable(),
  "LAP1 Kids": z.number().nullable(),
  "LAP1 Auditorium": z.number().nullable(),
  Christmas: z.number().nullable(),
  "Digital Giving GF": z.number().nullable(),
  "Pay Pal GF": z.number().nullable(),
  Bookstore: z.number().nullable(),
  "Café ": z.number().nullable(),
  "Message Sales": z.number().nullable(),
  "Granger High School": z.number().nullable(),
  "Granger Middle School": z.number().nullable(),
  "Elkhart HS": z.number().nullable(),
  "Elkhart MS": z.number().nullable(),
  "LaPorte HS": z.number().nullable(),
  "LaPorte MS": z.number().nullable(),
  "Attendance Gathering": z.number().nullable(),
  "Gathering Adult": z.number().nullable(),
  "Gathering Kids": z.number().nullable(),
  "Gathering Volunteer": z.number().nullable(),
  "Attendance ReEntry": z.number().nullable(),
  "ReEntry Guests": z.number().nullable(),
  "ReEntry Volunteers": z.number().nullable(),
  "Attendance Online": z.number().nullable(),
  F80: z.string().max(255).nullable(),
  F81: z.string().max(255).nullable(),
  F82: z.string().max(255).nullable(),
  F83: z.string().max(255).nullable(),
});

export type WeekendreportdataInput = z.infer<typeof WeekendreportdataSchema>;
